version: '3'
networks:
  kjr:
    driver: bridge
services:
  node:
    restart: always
    build: .
    ports:
      - 5000:80
    volumes:
      - ./:/app
    networks:
      - kjr
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
      
    volumes:
      - mongodb:/data/db
    networks:
      - kjr
volumes:
 mongodb: